//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContatoTelefone
    {
        public int ContatoTelefoneID { get; set; }
        public int ContatoID { get; set; }
        public int TipoTelefoneID { get; set; }
        public byte ContatoTelefoneDDD { get; set; }
        public int ContatoTelefoneNumero { get; set; }
    
        public virtual Contato Contato { get; set; }
        public virtual TipoTelefone TipoTelefone { get; set; }
    }
}
